@extends('layout::user.Frontend.master')

@section('title')
hotel
@endsection

@push('css')
<!-- aos css -->
<link rel="stylesheet" href="{{ asset('assets/Admin/assets/libs/aos/aos.css') }}" />

<!-------- Swiper Css Cdn --------->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/8.2.3/swiper-bundle.css" />

<style>
    .puff-in-center {
        -webkit-animation: puff-in-center 0.7s cubic-bezier(0.470, 0.000, 0.745, 0.715) both;
        animation: puff-in-center 0.7s cubic-bezier(0.470, 0.000, 0.745, 0.715) both;
    }

    /* ----------------------------------------------
         * Generated by Animista on 2022-7-26 13:5:55
         * Licensed under FreeBSD License.
         * See http://animista.net/license for more info.
         * w: http://animista.net, t: @cssanimista
         * ---------------------------------------------- */

    /**
         * ----------------------------------------
         * animation puff-in-center
         * ----------------------------------------
         */

    @keyframes puff-in-center {
        0% {
            -webkit-transform: scale(2);
            transform: scale(2);
            -webkit-filter: blur(4px);
            filter: blur(4px);
            opacity: 0;
        }

        100% {
            -webkit-transform: scale(1);
            transform: scale(1);
            -webkit-filter: blur(0px);
            filter: blur(0px);
            opacity: 1;
        }
    }


    /* loading sipner css strat*/
    .loading_spiner_ {
        /* margin-top: 20%; */
        border-radius: 8px;
        min-height: 57px;
        padding-top: 15px;
        display: flex;
        justify-content: center;
        align-items: center;
    }

    .loading_spiner_ .spinner {
        width: 2.5rem;
        aspect-ratio: 1;
        display: grid;
        -webkit-mask: conic-gradient(from 22deg, #0001, #000);
        mask: conic-gradient(from 22deg, #0001, #000);
        -webkit-animation: spin 1s steps(8) infinite;
        animation: spin 1s steps(8) infinite;
    }

    .loading_spiner_ .spinner,
    .loading_spiner_ .spinner:before {
        --gradient: linear-gradient(hsl(230deg 100% 20%) 0 0);
        background: var(--gradient) 50%/34% 8% space no-repeat, var(--gradient) 50%/8% 34% no-repeat space;
    }

    .loading_spiner_ .spinner:before {
        content: "";
        transform: rotate(45deg);
    }

    @-webkit-keyframes spin {
        to {
            transform: rotate(1turn);
        }
    }

    @keyframes spin {
        to {
            transform: rotate(1turn);
        }
    }

    /* loading sipner css end */
    .bed-selector .room {
        background: #FFFFFF;
        box-shadow: 0px 0px 19px rgb(0 0 0 / 10%);
        border-radius: 8px;
        height: 111px;
        width: 180px;
    }

    .bed-selector .room .title-container {
        display: flex;
        align-items: center;
        background: #E6E8F5;
        border-radius: 8px 8px 0px 0px;
    }

    .bed-selector .room .title-container .check {
        margin-right: 20px;
    }

    .bed-selector .dropdown-container {
        display: flex;
        align-items: center;
        justify-content: space-between;
        flex-wrap: wrap;
        /* height: 150px; */
        padding: 12px;
    }

    .bed-selector .dropdown-container .column {
        display: flex;
        flex-direction: column;
    }

    .bed-selector .dropdown-container .column .label {
        font-size: 14px;
    }

    .bed-selector .dropdown,
    .bed-selector .default-dropdown {
        width: 40px;
        height: 25px;
        margin: 10px auto;
    }

    .bed-selector .select-div {
        padding: 6px 10px;
        width: 130px;
        border: 1px solid #878996;
        border-radius: 5px
    }

    .bed-selector .option-none {
        display: none;
    }

    .bed-selector .select-option {
        position: absolute;
        z-index: 9999;
    }

    /*  */
    /* Css for select2  */
    section.check-in-out .check-in-out-bottom .select2 {
        width: 100% !important;
    }

    section.check-in-out .check-in-out-bottom .select2-container--default .select2-selection--single .select2-selection__arrow {
        height: 38px;
    }

    section.check-in-out .check-in-out-bottom .select2-container .select2-selection--single {
        height: 38px;
    }

    section.check-in-out .check-in-out-bottom .select2-container--default .select2-selection--single {
        border: 1px solid #878996;
        border-radius: 5px;
    }

    section.check-in-out .check-in-out-bottom .select2-container--default .select2-selection--single .select2-selection__rendered {
        color: #6A78C7;
        line-height: 35px;
    }

    section.check-in-out .check-in-out-bottom .select2-dropdown.select2-dropdown--below {
        width: 211px !important;
        height: 200px !important;
        border: 1px solid #878996;
        top: 10px !important;
    }

    .select2-container--open .select2-dropdown--above {
        max-width: 211px !important;
        max-height: 200px !important;
        border: 1px solid #878996;
        top: 0px !important;
    }

    .select2-container--default.select2-container--focus .select2-selection--multiple {
        border: 1px solid #aaa;
    }

    .select2-search--dropdown {
        display: none;
    }

    .select2-results__option {
        padding-right: 20px;
        vertical-align: middle;
    }

    .modal-body .small-box-main .small-box-single-img {
        border-radius: 7px;
        color: white;
        margin: 0;
        height: 35px;
        width: 35px;
        text-align: center;
        padding: 5px;
    }

    .result-main-inner .result-main-img .swiper-s-img .wishlist_icon_ {
        position: absolute;
        top: -33px;
        left: 17px;
        font-size: 15px;
        color: #fff;
        background-color: #6a78c7;
        width: 100%;
        max-width: 30px;
        height: 100%;
        max-height: 30px;
        border-radius: 500px;
        display: flex;
        justify-content: center;
        align-items: center;
        transition: all 0.5s;

    }

    .result-main-inner .result-main-img .swiper-s-img .wishlist_icon_.active {
        color: #ff0000e6;
        background-color: #fff;
    }

    .result-main-inner:hover .wishlist_icon_ {
        top: 14px !important;
        box-shadow: 0px 0px 3px #00000073;
    }

    .select2-container--default .select2-results__option--highlighted[aria-selected] {
        background-color: #6a78c7;
        color: white;
    }

    /* side contact button css  */

    .side-content .side-btn {
        padding: 4px 30px;
        background: #e6e8f5;
        border-radius: 100px;

    }

    .side-content .side-btn .btn {
        padding: 0;
        color: #6a78c7;
        font-size: 14px;
        line-height: 22px;
        font-weight: 800;
    }

    .hotels-result-search .input-group a {
        padding: 2px 20px;
        background: #e6e8f5;
        border-radius: 100px !important;
        font-size: 12px;
        line-height: 24px;
        color: #6a78c7;
        font-weight: 800;
    }

    .hotel-result .side-content .result-view {
        height: 30px;
    }

    /* media querry for bookingselect error */

    @media screen and (max-width:992px) {
        .hotel-result .bookingSelectError {
            position: absolute;
            bottom: -113px !important;
            left: 0 !important;
        }
    }

    @media screen and (min-width:406px) and (max-width:768px) {
        .hotel-result .bookingSelectError {
            position: absolute;
            bottom: -258px !important;
            left: 0 !important;
        }
    }

    @media screen and (max-width:406px) {
        .hotel-result .bookingSelectError {
            position: absolute;
            bottom: -272px !important;
            left: 0 !important;
        }
    }

    .slick-prev:before, .slick-next:before{
        font-size:25px;
    }

    .slick-prev{
        left:-40px;
    }

    .slick-next{
        right:-40px;
    }
    /* popup scroll */
    .reviews-popup-main .reviews-popup::-webkit-scrollbar-track {
        border-radius: 10px;
        background-color: transparent;
    }

    .reviews-popup-main .reviews-popup::-webkit-scrollbar {
        width: 7px;
        background-color: transparent;
    }

    .reviews-popup-main .reviews-popup::-webkit-scrollbar-thumb {
        border-radius: 20px;
        background-color: #a9a9a9;
    }

    /* media querry for bookingselect error */

    @media screen and (max-width:992px) {
        .hotel-result .bookingSelectError {
            position: absolute;
            bottom: -113px !important;
            left: 0 !important;
        }
    }

    @media screen and (min-width:406px) and (max-width:768px) {
        .hotel-result .bookingSelectError {
            position: absolute;
            bottom: -258px !important;
            left: 0 !important;
        }
    }

    @media screen and (max-width:406px) {
        .hotel-result .bookingSelectError {
            position: absolute;
            bottom: -272px !important;
            left: 0 !important;
        }
    }

    /* .slick-track {
        width: 620px !important;
    } */

    .img-popup-slider .img-swiper .slider-single img {
    width: 100%;
    object-fit: cover;
    }

    .img-popup-slider .img-swiper .slick-next:before {
        content: "\f105";
        font-family: "Font Awesome 5 Free";
        font-weight: 900;
    }

    .img-popup-slider .img-swiper .slick-prev:before {
        content: "\f104";
        font-family: "Font Awesome 5 Free";
        font-weight: 900;
    }

    .img-popup-slider .img-swiper {
        width: 100%;
        max-width: 857px;
        margin: 0 auto;
    }
     .slick-list .slick-track{
        width: 18710px !important;
    }
    .slick-track .slick-cloned,.slick-active{
        width: 76px !important;
    }
    .slick-list {
        padding: 0px 0px !important;
    }
    .slider-nav .slick-list .slick-track .slick-slide{
        width: 86px !important;
    }
    .slder-nav-img img{
        width: 82px !important;
    }
    .ImagepPopup {
        background:url("{{('assets/images/loading.gif')}}") 50% 50% no-repeat;
        width: 301px;
        height: 350px;
        display: inline-block;
    }
    
    .check-in-out-bottom .bed-selector  .select-bed-selector {
        cursor: pointer;
    }
    .hotels-results-amenities-popup{
        flex-wrap: wrap;
    }
    /* .amenitylabel{
        width: 25%;
    } */
    .amenityIcon{
        font-size: 12px;
    }
</style>
@endpush

@section('content')
<!------- Hotel-result Check-in-out section start ------->
<section class="check-in-out hotel-result py-3">
    <div class="container">
        <div class="check-in-out-inner" id="go_to_page">
            <h4>Hotels</h4>
            <div class="check-in-out-form">
                <div class="check-in-out-top">
                    <div class=" row align-items-center">
                        <div class="col-lg-6 mb-2">
                            <label for="hotels"></label>
                            <div class="d-flex align-items-center search-input">
                                <input class="form-control border-0" id="autocomplete" type="text"
                                    placeholder="Search Place" name="search" value="{{ request()->search }}">
                                <input type="hidden" id="latitude" name="latitude" class="form-control">
                                <input type="hidden" name="longitude" id="longitude" class="form-control">
                                <i class="fa-solid fa-magnifying-glass pe-3"></i>
                            </div>
                        </div>
                        <div class="col-lg-6 mb-2">
                            <form action="javascript: void(0);">
                                <div
                                    class="custom-calender-piker d-lg-flex justify-content-lg-center position-relative align-items-center">
                                    <div class="check-text-label pt-4 pe-xl-4 pe-lg-3">
                                        <label class="check-inout mt-2">Check-In</label>
                                        <div class="input--text d-flex align-items-center">
                                            <img src="{{ asset('assets/images/icons/cal-1.png') }}" class="px-2" alt="checkin" width="31" height="16">
                                            <input type="text" class="input--control ps-xl-2 check_in"
                                                name="value_from_start_date" placeholder="08/19/2020"
                                                data-datepicker="separateRange" value="{{ request()->checkIn }}" />
                                        </div>
                                    </div>
                                    <div class="check-text-label pt-4">
                                        <label class="check-inout check-out-label mt-2">Check-Out</label>
                                        <div class="input--text d-flex align-items-center">
                                            <img src="{{ asset('assets/images/icons/cal-2.png') }}" class="px-2" alt="checkout" width="31" height="16">
                                            <input type="text" class="input--control ps-xl-2 check_out"
                                                name="value_from_end_date" placeholder="08/19/2020"
                                                data-datepicker="separateRange" value="{{ request()->checkOut }}" />
                                        </div>
                                    </div>
                                    <span class="text-danger d-none bookingSelectError" style="position: absolute;bottom: -28px;
                                    left: 62px;">Please Select your trip date for booking room!</span>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="check-in-out-bottom">
                    <div class="row align-items-center">
                        <div class="col-lg-3 col-md-4 select-option pe-lg-0 mt-2">
                            <label>Guests</label>
                            <select class="form-control js-example-tags select_guest" name="guest">
                                @php
                                $selectGuest = Request()->guest;
                                @endphp
                                <option disabled>Select Guest</option>
                                <option {{ $selectGuest=='1' ? 'selected' : '' }}>1</option>
                                <option {{ $selectGuest=='2' ? 'selected' : '' }}>2</option>
                                <option {{ $selectGuest=='3' ? 'selected' : '' }}>3</option>
                                {{-- <option {{ $selectGuest=='4' ? 'selected' : '' }}>4</option>
                                <option {{ $selectGuest=='5' ? 'selected' : '' }}>5</option>
                                <option {{ $selectGuest=='6' ? 'selected' : '' }}>6</option>
                                <option {{ $selectGuest=='7' ? 'selected' : '' }}>7</option> --}}
                            </select>
                        </div>
                        <div class="col-lg-3 col-md-4 select-option pe-lg-0 mt-2">
                            @php
                            $selectRoom = Request()->room;
                            @endphp
                            <label>Room</label>
                            <select class="form-control js-example-tags select_room" name="room">
                                <option disabled>Select Room</option>
                                <option {{ $selectRoom=='1' ? 'selected' : '' }}>1</option>
                                <option {{ $selectRoom=='2' ? 'selected' : '' }}>2</option>
                                <option {{ $selectRoom=='3' ? 'selected' : '' }}>3</option>
                                {{-- <option {{ $selectRoom=='4' ? 'selected' : '' }}>4</option>
                                <option {{ $selectRoom=='5' ? 'selected' : '' }}>5</option>
                                <option {{ $selectRoom=='6' ? 'selected' : '' }}>6</option>
                                <option {{ $selectRoom=='7' ? 'selected' : '' }}>7</option> --}}
                            </select>
                        </div>

                        <div class="col-lg-3 col-md-4 select-option pe-lg-0 mt-2">
                            <label>Beds</label>
                            <div class="bed-selector ">
                                <div class="select-div d-flex justify-content-between align-items-center select-bed-selector">
                                    <i class="fa-solid fa-car" style="color: #878996"></i>
                                    <span style="color: #878996">king</span>
                                    <i class="fa-solid fa-caret-down" style="color: #878996"></i>
                                </div>
                                <div class="select-option select-room option-none">
                                    <div class="room">
                                        <div class="title-container">
                                            <h5 class="title" style="margin:10px;">Room 1</h5>
                                        </div>
                                        <section class="dropdown-container">
                                            <div class="dropdown-inner">
                                                <input class="form-check-input" type="checkbox" id="king_1">
                                                <label for="king_1">1 King</label>
                                            </div>
                                            <div class="dropdown-inner">
                                                <input class="form-check-input" type="checkbox" id="twin_1">
                                                <label for="twin_1">2 Twin</label>
                                            </div>
                                            <div class="dropdown-inner">
                                                <input class="form-check-input" type="checkbox" id="queen_1">
                                                <label for="queen_1">2 Queen</label>
                                            </div>
                                        </section>
                                    </div>
                                    <div class="room">
                                        <div class="title-container">
                                            <h5 class="title" style="margin:10px;">Room 1</h5>
                                        </div>
                                        <section class="dropdown-container">
                                            <div class="dropdown-inner">
                                                <input type="checkbox">
                                                <label for="">1 King</label>
                                            </div>
                                            <div class="dropdown-inner">
                                                <input type="checkbox">
                                                <label for="">2 Twin</label>
                                            </div>
                                            <div class="dropdown-inner">
                                                <input type="checkbox">
                                                <label for="">2 Queen</label>
                                            </div>
                                        </section>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="check-in-out-btn mt-5 mt-lg-4 text-xl-end text-center col-lg-3">
                            <a href="javascript:;" class="btn search-btn purple" id='SubmitSearch'>Search</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-------Hotel Result Check-in-out section end ------->
<!------- Search result Start ------->
<section class="hotel-result search-result pt-4 pb-5">
    <div class="container">
        <div class="search-result-inner">
            <div class="row">
                <div class="col-lg-3">
                    <aside class="side-content">
                        <div class="d-flex align-items-center justify-content-between result-view">
                            <span class="side-text">Viewing {{ $hotels->total() }} results</span>
                            <span class="side-btn ResetForm d-none">
                                <a href="javascript:;" id="ResetForm" class="btn reset-btn Resetform">Reset</a>
                            </span>
                            <button class="btn btn-filter-products-mobile d-block d-lg-none " type="button" data-bs-toggle="collapse" data-bs-target="#formReset" aria-expanded="false" aria-controls="formReset">
                                <i class="fas fa-filter me-2"></i>Filter Property                
                            </button>
                        </div>
                        <form class="hotel-result-form " id="formReset">
                            <div class="hotels-result-search">
                                <h5 class="search-heading">Search</h5>
                                <div class="input-group align-items-center search-input">
                                    <i class="fa-solid fa-magnifying-glass ps-2"></i>
                                    <input type="text" class="form-control propertyName searchProperty"
                                        name="propertyName" placeholder="Search by name"
                                        value="{{ request()->searchProperty }}">
                                    <a href="#" id="Apply" class="d-none">Apply</a>
                                    <span class="search-errors text-danger"></span>
                                </div>
                            </div>
                            <div class="hotels-result-sort pt-3">
                                <h5 class="search-heading ">Sort By</h5>
                                <div class="form-check ">
                                    <input class="form-check-input" type="checkbox" name="FilterCheck" value=""
                                        id="myPreferencesData">
                                    <div class="search-prefe-main d-flex justify-content-between align-items-center">
                                        <div class="search-prefe-text">
                                            <label class="form-check-label ps-2" for="myPreferencesData">
                                                My preferences
                                            </label>
                                        </div>
                                        <div class="search-prefe-icon">
                                            <a href="javascript:;" class="preferenceModal" data-bs-target="#myPreferences"><img
                                                    src="{{ asset('assets/images/icons/h-s-pluse.png') }}" width="24" height="24"></a>
                                                    @include('frontend::hotel.preference')
                                        </div>
                                    </div>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input sortBy" name="FilterCheck" type="checkbox" value="1"
                                        id="lowTohigh">
                                    <label class="form-check-label ps-2" for="lowTohigh">
                                        Price: low to high
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input sortBy" name="FilterCheck" type="checkbox" value=""
                                        id="HighToLowPrice">
                                    <label class="form-check-label ps-2" for="HighToLowPrice">
                                        Price: high to low
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input sortBy" name="FilterCheck" type="checkbox" value=""
                                        id="TopReviews">
                                    <label class="form-check-label ps-2" for="TopReviews">
                                        Top Review
                                    </label>
                                </div>
                                {{-- <div class="custom-filter mb-lg-0 mb-4">
                                    <a href="#"><img src="{{asset('assets/images/icons/h-s-pluse.png')}}" alt=""></a>
                                    <span class="custom-filter-text ps-2 purple"> Add Custom Filter</span>
                                    </label>
                                </div> --}}
                            </div>
                            <div class="hotels-filter result-mobile-view">
                                <div class="hotels-result-top-filter pt-2">
                                    <div class="small-heading">
                                        <h6>Top filters </h6>
                                    </div>
                                    <div class="form-check">
                                        <input class="form-check-input" name="FilterCheck" type="checkbox" value=""
                                            id="taxesFees">
                                        <label class="form-check-label ps-2" for="taxesFees">
                                            Final price with taxes fees
                                        </label>
                                    </div>
                                    <div class="form-check">
                                        <input class="form-check-input" name="FilterCheck" type="checkbox" value=""
                                            id="includedBreakfast">
                                        <label class="form-check-label ps-2" for="includedBreakfast">
                                            Breakfast Included
                                        </label>
                                    </div>
                                    <div class="form-check">
                                        <input class="form-check-input" name="FilterCheck" type="checkbox" value=""
                                            id="flexCheckCheckedCheckIn">
                                        <label class="form-check-label ps-2" for="flexCheckCheckedCheckIn">
                                            Flexible Check-In
                                        </label>
                                    </div>
                                    <div class="form-check">
                                        <input class="form-check-input" name="FilterCheck" type="checkbox" value=""
                                            id="checkOut_flexible">
                                        <label class="form-check-label ps-2" for="checkOut_flexible">
                                            Flexible Check-Out
                                        </label>
                                    </div>
                                </div>
                                <div class="hotels-result-style pt-1">
                                    <div class="small-heading">
                                        <h6>Style </h6>
                                    </div>
                                    <div class="form-check ">
                                        <input class="form-check-input" type="checkbox" name="FilterCheck" value=""
                                            id="modernData">
                                        <label class="form-check-label ps-2" for="modernData">
                                            Modern
                                        </label>
                                    </div>
                                    <div class="form-check ">
                                        <input class="form-check-input" type="checkbox" name="FilterCheck" value=""
                                            id="Historic_nav">
                                        <label class="form-check-label ps-2" for="Historic_nav">
                                            Historic
                                        </label>
                                    </div>
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" name="FilterCheck" value=""
                                            id="Contemporarynav">
                                        <label class="form-check-label ps-2" for="Contemporarynav">
                                            Contemporary
                                        </label>
                                    </div>
                                </div>
                                <div class="hotels-result-budget pt-1">
                                    <div class="small-heading">
                                        <h6>Budget </h6>
                                    </div>
                                    <div class="row g-0  align-items-center ">
                                        <div class="col-4 col-lg-5">
                                            <input type="number" class="form-control budgetMin" placeholder="$ Min"
                                                value="{{request()->budgetMin}}">
                                        </div>
                                        <div class="col-2 p-0 text-center">
                                            <span class="form-text">to</span>
                                        </div>
                                        <div class="col-4 col-lg-5">
                                            <input type="number" class="form-control budgetMax" placeholder="$ Max"
                                                value="{{request()->budgetMax}}">
                                        </div>
                                    </div>
                                </div>
                                <div class="hotels-result-property pt-4">
                                    <div class="small-heading">
                                        <h6>Property Class </h6>
                                    </div>
                                    <div class="form-check">
                                        <input class="form-check-input starRating" type="checkbox" name="FilterCheck"
                                            value="5" id="star_5" {{ request()->starRating == 5 ? 'checked' : ''}}>
                                        <label for="star_5">
                                            <span class="property-class-icon ps-2"><img
                                                    src="{{ asset('assets/images/icons/start.png') }}" width="12" height="12" alt="star"></span>
                                            <span class="property-class-icon"><img
                                                    src="{{ asset('assets/images/icons/start.png') }}" width="12" height="12" alt="star"></span>
                                            <span class="property-class-icon "><img
                                                    src="{{ asset('assets/images/icons/start.png') }}" width="12" height="12" alt="star"></span>
                                            <span class="property-class-icon "><img
                                                    src="{{ asset('assets/images/icons/start.png') }}" width="12" height="12" alt="star"></span>
                                            <span class="property-class-icon "><img
                                                    src="{{ asset('assets/images/icons/start.png') }}" width="12" height="12" alt="star"></span>
                                        </label>
                                    </div>
                                    <div class="form-check">
                                        <input class="form-check-input starRating" type="checkbox" name="FilterCheck"
                                            value="4" id="star_4" {{ request()->starRating == 4 ? 'checked' : ''}}>
                                        <label for="star_4">
                                            <span class="property-class-icon ps-2"><img
                                                    src="{{ asset('assets/images/icons/start.png') }}" width="12" height="12" alt="star"></span>
                                            <span class="property-class-icon "><img
                                                    src="{{ asset('assets/images/icons/start.png') }}" width="12" height="12" alt="star"></span>
                                            <span class="property-class-icon "><img
                                                    src="{{ asset('assets/images/icons/start.png') }}" width="12" height="12" alt="star"></span>
                                            <span class="property-class-icon "><img
                                                    src="{{ asset('assets/images/icons/start.png') }}" width="12" height="12" alt="star"></span>
                                        </label>
                                    </div>
                                    <div class="form-check">
                                        <input class="form-check-input starRating" type="checkbox" name="FilterCheck"
                                            value="3" id="star_3" {{ request()->starRating == 3 ? 'checked' : ''}}>
                                        <label for="star_3">
                                            <span class="property-class-icon ps-2"><img
                                                    src="{{ asset('assets/images/icons/start.png') }}" width="12" height="12" alt="star"></span>
                                            <span class="property-class-icon "><img
                                                    src="{{ asset('assets/images/icons/start.png') }}" width="12" height="12" alt="star"></span>
                                            <span class="property-class-icon "><img
                                                    src="{{ asset('assets/images/icons/start.png') }}" width="12" height="12" alt="star"></span>
                                        </label> 
                                    </div>
                                    <div class="form-check">
                                        <input class="form-check-input starRating" type="checkbox" name="FilterCheck"
                                            value="2" id="star_2" {{ request()->starRating == 2 ? 'checked' : ''}}>
                                        <label for="star_2">
                                            <span class="property-class-icon ps-2"><img
                                                    src="{{ asset('assets/images/icons/start.png') }}" width="12" height="12" alt="star"></span>
                                            <span class="property-class-icon "><img
                                                    src="{{ asset('assets/images/icons/start.png') }}" width="12" height="12" alt="star"></span>
                                        </label>
                                    </div>
                                    <div class="form-check">
                                        <input class="form-check-input starRating" type="checkbox" name="FilterCheck"
                                            value="1" id="star_1" {{ request()->starRating == 1 ? 'checked' : ''}} >
                                        <label for="star_1">
                                            <span class="property-class-icon ps-2"><img
                                                    src="{{ asset('assets/images/icons/start.png') }}" width="12" height="12" alt="star"></span>
                                        </label>
                                    </div>
                                </div>
                                <div class="hotels-results-neigh pt-2">
                                </div>
                                <div class="hotels-results-amenities pt-1">
                                    <div class="small-heading">
                                        <h6>Amenities </h6>
                                    </div>
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" name="FilterCheck" value=""
                                            id="AllAmenities">
                                        <label class="form-check-label ps-2 amenityValue" for="AllAmenities">
                                            All Amenities
                                        </label>
                                    </div>
                                    @foreach ($amenities as $amenity)
                                    <div class="form-check">
                                        <input class="form-check-input ps-2 amenityValue" type="checkbox"
                                            name="FilterCheck" value="" id="flexCheckChecked_{{$amenity->id}}">
                                        <label class="form-check-label  ps-2 " for="flexCheckChecked_{{$amenity->id}}">
                                            {{ @$amenity->amenities }}
                                        </label>
                                        <span class="amenities-icon">
                                            <i class="{{ @$amenity->icon }}"></i>
                                        </span>
                                    </div>
                                    @endforeach
                                </div>
                                <div class="hotels-result-filter-btn text-center pb-4">
                                    <a href="javascript:;" class="btn bg-purple filter-btn filterButton">Filter</a>
                                </div>
                            </div>
                        </form>
                    </aside>
                </div>
                <!-------- Search Hotel Result -------->
                <div class="col-lg-9 position-relative hotelResultDiv mt-4 mt-lg-0">
                    <input type="hidden" class="last_page_value" value="{{$hotels->lastPage()}}">
                    <input type="hidden" class="total_page" value="{{$hotels->total()}}">
                    @if (count($propertyTypeCounts))
                        <div class="select--your-destination mainDivPropertyType d-none">
                            <div class="cat propertyTypeCheckDiv">
                            <label>
                                <input type="checkbox" class="propertyTypeCheckbox"  name="propertyType" value="All"><span>All ({{@$propertyTypeCounts->count()}})</span>
                            </label>
                            </div>
                            @if (@$propertyTypes)
                                @foreach ($propertyTypes as $propertyType)
                                    <div class="cat propertyTypeCheckDiv">
                                    <label>
                                        <input type="checkbox" class="P_TypeCheckbox"  name="propertyType" value="{{$propertyType->slug}}" ><span>
                                            @php
                                                $propertyId = $propertyTypeCounts->where('property_id',$propertyType->id)->count();
                                            @endphp
                                            {{$propertyType->type}} ({{$propertyId}})</span>
                                    </label>
                                    </div>
                                @endforeach
                            @endif
                        </div>
                    @endif
                    @include('frontend::hotel.hotelResult')

                    {{-- No data found box --}}
                    <main data-aos="fade-up" data-aos-easing="linear" data-aos-duration="1000"
                        class="result-main-content border-semidark mt-4 d-none hotel_empty">
                        <div class="result-main-inner d-flex align-items-center justify-content-center"
                            style="width: 966px;height: 345px;">
                            <div class="empty-table w-100 text-center py-5">
                                <lord-icon src="https://cdn.lordicon.com/msoeawqm.json" trigger="loop"
                                    colors="primary:#405189,secondary:#0ab39c" style="width:75px;height:75px">
                                </lord-icon>
                                <h4>No Property Found.</h4>
                                {{-- <h6>Add a new record by simpley clicking the button on right side.</h6> --}}
                            </div>
                        </div>
                    </main>
                </div>
                <!-------- Search Hotel Result end -------->

            </div>
        </div>
    </div>
    </div>
</section>
<!------- Search result end ------->
<div class="mainReviewPopupDiv">
    @if (isset($hotelRating))
        @include('frontend::hotel.review')  
    @endif
</div>
<div class="popupImage">
    @if (isset($hotelPhotos))
        @include('frontend::hotel.popup-image')
    @endif
</div>
<div class="mainPaymentPopupDiv">
    @if (isset($hotel) && $hotel != '')
        @include('frontend::hotel.payment')
    @endif
</div>

@endsection

@push('script')
<!------- Custom JS Link -----  -->
<script src="{{ asset('assets/js/custom.js') }}"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>


@if (session()->get('booking'))
<script>
    $(document).ready(function() {
                $('#success_payment').modal('show');
                setTimeout(function() {
                    $('#success_payment').modal('hide')
                }, 4000);
            });
</script>
@endif
@if (session()->get('error'))
<script>
    $(document).ready(function() {
                $('#payment_error_').modal('show');
                setTimeout(function() {
                    $('#payment_error_').modal('hide')
                }, 4000);
            });
</script>
@endif

@php
    $paypalId = config('paypal.sandbox.client_id');
@endphp


<!-- aos js -->
<script src="{{ asset('assets/Admin/assets/libs/aos/aos.js') }}"></script>

<!-- animation init -->
<script src="{{ asset('assets/Admin/assets/js/pages/animation-aos.init.js') }}"></script>

<!------- loading icon link -------->
<script src="{{ asset('assets/Admin/assets/js/pages/plugins/lord-icon-2.1.0.js') }}"></script>

<!-------- Google Place Search -------->
<script type='text/javascript'
    src='https://maps.googleapis.com/maps/api/js?libraries=places&v=3&language=En&key=AIzaSyBZhREk9TESs69r99eYGKkIQ725IqOP8Zc&ver=5.9.3'>
</script>

<script>
    $(document).on('click','.preferenceModal', function(){
        $('.mypreferences-popup').modal('show');
    });
</script>
<!-------- Weather swiper js start--------->
<script>
    // Google Place Search
        google.maps.event.addDomListener(window, 'load', initialize);

        function initialize() {
            var input = document.getElementById('autocomplete');
            var autocomplete = new google.maps.places.Autocomplete(input);
            autocomplete.addListener('place_changed', function() {
                var place = autocomplete.getPlace();
                $('#latitude').val(place.geometry['location'].lat());
                $('#longitude').val(place.geometry['location'].lng());

                $("#latitudeArea").removeClass("d-none");
                $("#longtitudeArea").removeClass("d-none");
            });

        }
        
        const swiper = new Swiper(".swiper", {
            slidesPerGroup: 1,
            loop: false,
            Infinity: true,
            navigation: {
                nextEl: ".swiper-button-next",
                prevEl: ".swiper-button-prev",
            },
            speed: 400,
            slidesPerView: 7,
            spaceBetween: 7,
            //     breakpoints: {
            //         900: {
            //             slidesPerView: 10,
            //             spaceBetween: 10,
            //             slidesOffsetAfter: 200,
            //         },
            // },
        });
</script>
<!-------- Weather swiper js end--------->

<!-------- image popup (slider image js)------>
<script>
        $(function () {
            $('.ImagepPopup img').hide();
        });

        var i = 0;
        var int=0;
        $(window).bind("load", function() {

            var int = setInterval("doThis(i)",500);

        });

        function doThis() {
            var images = $('.ImageLoad').length;
            if (i >= images) {
                clearInterval(int);
            }
            $('.ImageLoad:hidden').eq(0).fadeIn(500);
            i++;
        } 

    function slider(){
        $('.slider-single').slick({
            slidesToShow: 1,
            slidesToScroll: 1,
            arrows: true,
            draggable: true,
            fade: true,
            asNavFor: '.slider-nav'
        });

        $('.slider-nav').slick({
            slidesToShow: 10,
            slidesToScroll: 1,
            asNavFor: '.slider-single',
            dots: false,
            draggable: true,
            centerMode: true,
            arrows: false,
            focusOnSelect: true,
            responsive: [{
                    breakpoint: 1024,
                    settings: {
                        slidesToShow: 8,
                        slidesToScroll: 1,
                    },
                },
                {
                    breakpoint: 767,
                    settings: {
                        slidesToShow: 7,
                        slidesToScroll: 1,
                    },
                },
                {
                    breakpoint: 600,
                    settings: {
                        slidesToShow: 6,
                        slidesToScroll: 1,
                    },
                },
                {
                    breakpoint: 576,
                    settings: {
                        slidesToShow: 5,
                        slidesToScroll: 1,
                    },
                },
                {
                    breakpoint: 480,
                    settings: {
                        slidesToShow: 3,
                        slidesToScroll: 1,
                    },
                },
                {
                    breakpoint: 360,
                    settings: {
                        slidesToShow: 2,
                        slidesToScroll: 1,
                    },
                },
            ],
        });
    }

        $(document).on('click','.ImagepPopup',function(){
            var id = $(this).data('id');

            formdata = new FormData();
            formdata.append('id', id);
            
            $.ajax({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                url: "{{route('image.hotel')}}",
                type: "POST",
                processData: false,
                contentType: false,
                data: formdata,
                    success: function (response) {
                    // console.log(response);
                    $('.popupImage').html(response);
                    $('.slick-prev').trigger('click');
                    $('.img-popup-slider').modal('show');
                    slider();
                }, error:function (response) {
                    console.log('error');
                }
            });
        });
        // $('.modal').on('shown.bs.modal', function(e) {
        //     $('.slider-single').slick('setPosition');
        //     $('.swiper').addClass('open');
        // });

        // $('.modal').on('shown.bs.modal', function(e) {
        //     $('.slider-nav').slick('setPosition');
        //     $('.swiper').addClass('open');
        // });


        $(document).on('click', '#SubmitSearch', function() {
            submitHotelBtn();
        });

        function submitHotelBtn() {
            var search = $("input[name=search]").val();
            !search ? $(`.search-error`).html(`Please enter a destination to start searching.`) : $(`.search-error`)
                .html(``);
            var checkIn = $("input[name=value_from_start_date]").val();
            var checkOut = $("input[name=value_from_end_date]").val();
            var guest = $("select[name=guest]").val();
            var room = $("select[name=room]").val();

            var bed = new Array();
            $('input[name="bed"]:checked').each(function() {
                bed.push($(this).val());
            });

            if (!search) {
                return;
            }

            var propertyTypeCheckBox = [];
            $.each($("input[class='P_TypeCheckbox']:checked"), function(){
                propertyTypeCheckBox.push($(this).val());
            });
            var propertyTypeName = propertyTypeCheckBox.join(",");

            if(propertyTypeName){
                window.location.href = base_url + "/search?search=" + search + "&checkIn=" + checkIn + "&checkOut=" +
                    checkOut + "&guest=" + guest + "&room=" + room + "&bed=" + bed + '&propertyTypeName=' + propertyTypeName;
            }else{
                window.location.href = base_url + "/search?search=" + search + "&checkIn=" + checkIn + "&checkOut=" +
                    checkOut + "&guest=" + guest + "&room=" + room + "&bed=" + bed;
            }
        }

        $(document).on('click', '#Apply', function(e) {

            var searchProperty = $(".searchProperty").val();
            // console.log(searchProperty);
            // !searchProperty ? $(`.search-errors`).html(`Please enter a destination to start searching.`) : $(`.search-errors`)
            //     .html(``);

            // if (!searchProperty) {
            //     return;
            // }

            window.location.href = base_url + "/search?searchProperty=" + searchProperty;
        });

        $(document).on('click', '.filterButton', function(){
            var propertyName = $('.propertyName').val();
            var budgetMax = $('.budgetMax').val();
            var budgetMin = $('.budgetMin').val();
            var starRating = $('.starRating:checked').val();

            // var sortBy = $('.sortBy').val();
            // var topFilter = $('.topFilter').val();
            // var style = $('.style').val();
            // var propertyStar = $('.propertyStar').val();
            // var amenityValue = $('.amenityValue').val();
            // // alert(propertyName);

            if (!propertyName) {
                return;
            }
            window.location.href = baseUrl  + "/search?propertyName=" + propertyName + '&budgetMin=' + budgetMin + '&budgetMax=' + budgetMax + '&starRating=' + starRating;
        });

</script>
<!-- custom-selector js -->
<script>
    $(document).ready(function() {

            $(document).on('click', '.select-div', function() {
                $('.select-room').html('');
                var index = $('.select_room').val();
                for (var i = 1; i <= index; i++) {
                    $number = i;
                    addRoom($number);
                }
                $(".select-option").toggleClass("option-none");
            });

            $(".js-example-tags").select2({
                tags: true
            });

            $(document).on("click", function(event) {
                var $trigger = $(".bed-selector");
                if ($trigger !== event.target && !$trigger.has(event.target).length) {
                    $(".select-room").addClass("option-none");
                }
            });

            function addRoom($number) {
                let searchParams = new URLSearchParams(window.location.search);

                var king = '';
                var queen = '';
                var twin = '';
                if(searchParams && searchParams.has('bed')){
                    let bed = searchParams.get('bed').split(",");
                    if(bed.includes('King')){
                        king = 'checked';
                    }
                    if(bed.includes('Queen')){
                        queen = 'checked';
                    }
                    if(bed.includes('twin')){
                        twin = 'checked';
                    }
                }
                $room = $(`<div class="room"><div class="title-container">
                            <h5 class="title" style="margin:10px;">Room ` + $number + `</h5>
                        </div>
                        <section class="dropdown-container">
                            <div class="dropdown-inner">
                                <input class="form-check-input hotelBeds" type="checkbox" name="bed" id="king_` + $number + `" value="King"`+ king +`>
                                <label for="king_` + $number + `">1 King</label>
                            </div>
                            <div class="dropdown-inner">
                                <input class="form-check-input hotelBeds" type="checkbox" name="bed" id="twin_` + $number + `" value="twin"`+ twin +`>
                                <label for="twin_` + $number + `">2 Twin</label>
                            </div>
                            <div class="dropdown-inner">
                                <input class="form-check-input hotelBeds" type="checkbox" name="bed" id="queen_` + $number + `" value="Queen"`+  queen +` >
                                <label for="queen_` + $number + `">2 Queen</label>
                            </div>
                        </section>
                    </div>`);
                $('.select-room').append($room);
            }

        });
</script>

<script>
    $('.loading_spiner_').addClass('d-block');

$(document).ready(function(){

    var baseUrl = $('#base_url').val();

    // CSRF TOKEN
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content'),
            'X-Requested-With': 'XMLHttpRequest'
        }
    });

    var page = 2;
    infinteLoadMore(page);

    // $(window).scroll(
    document.addEventListener('scroll',function (e) {
        e.preventDefault();
        if ($(window).scrollTop() + ($(window).height() + 250) >= $(document).height()) {
            page++;
            var paginate = $('.last_page_value').val();
            if(paginate >= page){
                infinteLoadMore(page);
            }
        }
    });

    // load hotel Detail
    function infinteLoadMore(page) {
        var search = $("input[name=search]").val();
        var checkIn = $("input[name=value_from_start_date]").val();
        var checkOut = $("input[name=value_from_end_date]").val();
        var guest = $("select[name=guest]").val();
        var room = $("select[name=room]").val();
        var bed = new Array();
        $('input[name="bed"]:checked').each(function() {
            bed.push(this.value);
        });
        var propertyName = $("input[name=propertyName]").val();

        var searchProperty = $('.searchProperty').val();

        // propertyType
        let propertyTypeUrl = new URLSearchParams(window.location.search);
        propertyTypeUrl.has('propertyType');
        let propertyType = propertyTypeUrl.get('propertyType');

        // city
        let CityUrl = new URLSearchParams(window.location.search);
        CityUrl.has('City');
        let City = CityUrl.get('City');


        // var propertyTypeCheckBox = [];
        //     $.each($("input[class='P_TypeCheckbox']"), function(){
        //         propertyTypeCheckBox.push($(this).val());
        //     });
        //     var propertyTypeName = propertyTypeCheckBox.join(",");
        var propertyTypeCheckBox = [];
        $.each($("input[class='P_TypeCheckbox']:checked"), function(){
            propertyTypeCheckBox.push($(this).val());
        });
        var propertyTypeName = propertyTypeCheckBox.join(",");


        if(search){
            $.ajax({

                url: baseUrl  + "/search?page=" + page + "&search=" + search + "&checkIn=" + checkIn + "&checkOut=" + checkOut + "&guest=" + guest + "&room=" + room + "&bed=" + bed + "&propertyTypeName=" + propertyTypeName,
                datatype: "html",
                type: "get",
                beforeSend: function () {
                $('.loading_spiner_').removeClass('d-none');
                }
            })
            .done(function (response) {
                $('.loading_spiner_').addClass('d-none');
                var total_page = $('.total_page').val();
                $('.mainDivPropertyType').removeClass('d-none');
                if(total_page == 0){
                // $('.mainDivPropertyType').addClass('d-none');
                    $('.hotel_empty').removeClass('d-none');
                }
                // console.log(response);
                $(".hotelResultDiv").append(response);
            })
            .fail(function (jqXHR, ajaxOptions, thrownError) {
                console.log('Server error occured');
            });

        } else if(searchProperty) {
            $.ajax({

                url: baseUrl  + "/search?page=" + page + "&searchProperty=" + searchProperty,
                datatype: "html",
                type: "get",
                beforeSend: function () {
                $('.loading_spiner_').removeClass('d-none');
                }
            })
            .done(function (response) {
                $('.loading_spiner_').addClass('d-none');
                var total_page = $('.total_page').val();
                if(total_page == 0){
                    $('.hotel_empty').removeClass('d-none');
                }
                $(".hotelResultDiv").append(response);
            })
            .fail(function (jqXHR, ajaxOptions, thrownError) {
                console.log('Server error occured');
            });
        } else if(propertyName) {
            $.ajax({

                url: baseUrl  + "/search?page=" + page + "&propertyName=" + propertyName + '&budgetMin=' + budgetMin + '&budgetMax=' + budgetMax + '&starRating=' + starRating,
                datatype: "html",
                type: "get",
                beforeSend: function () {
                $('.loading_spiner_').removeClass('d-none');
                }
            })
            .done(function (response) {
                $('.loading_spiner_').addClass('d-none');
                var total_page = $('.total_page').val();
                if(total_page == 0){
                    $('.hotel_empty').removeClass('d-none');
                }
                $(".hotelResultDiv").append(response);
            })
            .fail(function (jqXHR, ajaxOptions, thrownError) {
                console.log('Server error occured');
            });
        } else if(propertyType){
            $.ajax({

                url: baseUrl  +  "/search?page=" + page + "&propertyType=" + propertyType,
                datatype: "html",
                type: "get",
                beforeSend: function () {
                $('.loading_spiner_').removeClass('d-none');
                }
                })
                .done(function (response) {
                $('.loading_spiner_').addClass('d-none');
                var total_page = $('.total_page').val();
                if(total_page == 0){
                    $('.hotel_empty').removeClass('d-none');
                }
                    $(".hotelResultDiv").append(response);
                })
                .fail(function (jqXHR, ajaxOptions, thrownError) {
                console.log('Server error occured');
                });
        } else if(City){
            $.ajax({
                url: baseUrl  +  "/search?page=" + page + "&City=" + City,
                datatype: "html",
                type: "get",
                beforeSend: function () {
                $('.loading_spiner_').removeClass('d-none');
                }
                })
                .done(function (response) {
                $('.loading_spiner_').addClass('d-none');
                var total_page = $('.total_page').val();
                if(total_page == 0){
                    $('.hotel_empty').removeClass('d-none');
                }
                    $(".hotelResultDiv").append(response);
                })
                .fail(function (jqXHR, ajaxOptions, thrownError) {
                console.log('Server error occured');
                });
        } else {
            $.ajax({

                url: baseUrl + "/search?page=" + page,
                datatype: "html",
                type: "get",
                beforeSend: function () {
                    $('.loading_spiner_').removeClass('d-none');
                }
            })
            .done(function (response) {
                $('.loading_spiner_').addClass('d-none');
                var total_page = $('.total_page').val();
                if(total_page == 0){
                    $('.hotel_empty').removeClass('d-none');
                }
                $(".hotelResultDiv").append(response);
            })
            .fail(function (jqXHR, ajaxOptions, thrownError) {
                console.log('Server error occured');
            });
        }
    }



    $(document).on('click', '.addWishlist', function(){
        let hotelId = $(this).data('id');

        $(this).addClass('removeWishlist active');
        $(this).removeClass('addWishlist');

        if (!hotelId) {
            return;
        }

        formdata = new FormData();
        formdata.append('hotelId', hotelId);

        $.ajax({
            url: "{{route('add.wishlist')}}",
            type: "POST",
            processData: false,
            contentType: false,
            data: formdata,
            success: function (response) {
                // console.log('done');
            }, error:function (response) {
                console.log('fail');
            }
        });
    });

    $(document).on('click', '.removeWishlist', function(){
        let hotelId = $(this).data('id');

        $(this).removeClass('removeWishlist active');
        $(this).addClass('addWishlist');

        if (!hotelId) {
            return;
        }

        formdata = new FormData();
        formdata.append('hotelId', hotelId);

        $.ajax({
            url: "{{route('remove.wishlist')}}",
            type: "POST",
            processData: false,
            contentType: false,
            data: formdata,
            success: function (response) {
                // console.log('done');
            }, error:function (response) {
                console.log('fail');
            }
        });
    });

    $(document).on('click', '.Resetform', function(e){
        e.preventDefault();
        $("#formReset")[0].reset();
        resetFilter();
    });

    $(document).on('keyup', '.searchProperty', function(){
        var searchProperty = $(this).val().length;
        searchPropertyData(searchProperty);
        ResetPropertyData(searchProperty);
    });

    function searchPropertyData(searchProperty) {
        if(searchProperty >= 1){
            $('#Apply').removeClass('d-none');
        }else{
            $('#Apply').addClass('d-none');
        }
    }

    function ResetPropertyData(searchProperty){
        if(searchProperty >= 1){
            $('.ResetForm').removeClass('d-none');
        }else{
            $('.ResetForm').addClass('d-none');
        }
    }

    $(document).on('keyup', '.budgetMin', function(){
        var searchProperty = $(this).val().length;
        ResetPropertyData(searchProperty);
    });

    $(document).on('keyup', '.budgetMax', function(){
        var searchProperty = $(this).val().length;
        ResetPropertyData(searchProperty);
    });

    function resetFilter() {
        if($('input[type="checkbox"]:checked').length > 0){
            $('.ResetForm').removeClass('d-none');
        }else{
            $('.ResetForm').addClass('d-none');
        }

        $('input[type="checkbox"]').change(function() {
            if($('input[name="FilterCheck"]:checked').length > 0){
                $('.ResetForm').removeClass('d-none');
            }else{
                $('.ResetForm').addClass('d-none');
            }
        });
    }
    resetFilter();

    
});
</script>


<script>
    $(document).on('click','.hotelPriceBtn',function (e) {
        $('.bookingSelectError').removeClass("d-none");
	    e.preventDefault();
        $("html, body").animate({
            scrollTop: 0
        }, "fast");
        return false;
	});

    $(document).on('click', '.reviewPopup', function(e) {
        e.preventDefault();

        var hotel_id = $(this).data('id');

        formdata = new FormData();
        formdata.append('hotel_id', hotel_id);

        $.ajax({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            },
            url: "{{route('hotel.review')}}",
            type: "POST",
            processData: false,
            contentType: false,
            data: formdata,
            success: function (response) {
                $('.mainReviewPopupDiv').html(response);
                $('.reviews-popup-main').modal('show');
            }, error:function (response) {
                console.log(response);
            }
        });
    });
</script>

<script>
    $(document).ready(function(){

        $('.propertyTypeCheckbox').click(function(){
            if(this.checked){
                $('.P_TypeCheckbox').each(function(){
                    this.checked = false;
                });
                setTimeout(function(){
                    submitHotelBtn();
                },50);
            }
        });

        $('.P_TypeCheckbox').click(function(){
            if(this.checked){
                $('.propertyTypeCheckbox').each(function(){
                    this.checked = false;
                });
            }
            setTimeout(function(){
                submitHotelBtn();
            },50);
        });

        function setUrlValue() {
            let propertyTypeData = new URLSearchParams(window.location.search);

            if(propertyTypeData && propertyTypeData.has('propertyTypeName')){
                let property = propertyTypeData.get('propertyTypeName').split(",");

                if(property.includes('hotel')){
                    $('.P_TypeCheckbox[value=hotel]').attr('checked', true);
                }
                if(property.includes('guest-house')){
                    $('.P_TypeCheckbox[value=guest-house]').attr('checked', true);
                }
                if(property.includes('homestay')){
                    $('.P_TypeCheckbox[value=homestay]').attr('checked', true);
                }
                if(property.includes('hostel')){
                    $('.P_TypeCheckbox[value=hostel]').attr('checked', true);
                }
                if(property.includes('farm-stay')){
                    $('.P_TypeCheckbox[value=farm-stay]').attr('checked', true);
                }
            }else{
                $('.propertyTypeCheckbox').attr('checked', true);
            }

            $('.select-div').trigger('click');
            $('.select-room').addClass('option-none');
        }
        setUrlValue();
    

        $(document).on('click', '.hotelPayment', function(e){
            e.preventDefault();

            var hotelId = $(this).data('id');

            formdata = new FormData();
            formdata.append('hotelId', hotelId);

            $.ajax({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                url: "{{route('hotel.payment')}}",
                type: "POST",
                processData: false,
                contentType: false,
                data: formdata,
                success: function (response) {
                    $('.mainPaymentPopupDiv').html(response);
                    $('#payment_details_popup').modal('show');
                }, error:function (response) {

                }
            });
        });
    });
</script>

@if (isset($hotel) && $hotel != '')
{{-- paypal cdn --}}
<script src="https://www.paypal.com/sdk/js?client-id={{ $paypalId }}&currency=USD"></script>
{{-- stripe cdn--}}
<script type="text/javascript" src="https://js.stripe.com/v3/"></script>
<script src="https://checkout.stripe.com/v3/checkout.js"></script>
{{-- razorpay cdn --}}
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>
    // razorpay payment gateway
    $(document).on('click', '.payment_button_Razorpay', function(e){
        e.preventDefault();
        var id = $(this).data('id');
        var amount = $('.amount_data_'+id).val();
        var total_amount = amount+"00";
        var image = $('.logoImage').attr('src');
        var hotel_id = $('.hotel_id_'+id).val();
        var payment_id = $('.razorpay_payment_id').val();
        var room_id = $('.room_id_'+id).val();
        var start_date = $('.check_in').val();
        var end_date = $('.check_out').val();

        var options = {
        "key": "{{config('services.razorpay.key')}}",
        "amount": total_amount,
        "currency": "INR",
        "name": "NiceSnippets",
        "description": "Test Transaction",
        "image": image,
        "order_id": "",
        "handler": function (response){
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            $.ajax({
                type:'POST',
                url:"{{ route('payment.razorpay') }}",
                data:{razorpay_payment_id:response.razorpay_payment_id, amount:amount, hotel_id:hotel_id, payment_id:payment_id, room_id:room_id, start_date: start_date, end_date : end_date},
                success:function(data){
                    $('.payment_details_popup').hide();
                    $('.modal-backdrop').hide();
                    $("#success_payment").modal("toggle");
                    $('.bookingId').val('Booking Ref :'+ data.bookingId);
                }
            });
        },
        "prefill": {
            "name": "demo",
            "email": "dem@examle.com",
            "contact": "1234567890"
        },
        "notes": {
            "address": "test test"
        },
        "theme": {
            "color": "#6a78c7"
        }
        };
        var rzp1 = new Razorpay(options);
        rzp1.open();
    });
</script>
<script>
    const stripe =  Stripe("{{ config('services.stripe.key') }}");

    $(document).on('click', '.payment_button_Stripe', function(e){
        var id = $(this).data('id');
        var amount = $('.amount_data_'+id).val();
        var total_amount = amount+"00";
        var payment_id = $('.stripe_payment_id').val();
        var property_name = $(this).data('value');
        var hotel_id = $('.hotel_id_'+id).val();
        var room_id = $('.room_id_'+id).val();
        var start_date = $('.check_in').val();
        var end_date = $('.check_out').val();

        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        $.ajax({
            type:'POST',
            url:"{{ route('show.stripe') }}",
            data: {amount : amount, total_amount : total_amount,property_name : property_name, hotel_id : hotel_id, payment_id : payment_id, room_id : room_id, start_date : start_date, end_date : end_date},
            success:function(response){

                stripe.redirectToCheckout({
                    sessionId : response.session.id,
                })
            },error:function (response) {
                console.log('fail');
            }
        });
    });

    $(document).on('click', '.payment_button_Paypal', function(e){
        e.preventDefault();
        var id = $(this).data('id');
        var amount = $('.amount_data_'+id).val();
        var total_amount = amount+"00";
        var payment_id = $('.paypal_payment_id').val();
        var property_name = $(this).data('value');
        var hotel_id = $('.hotel_id_'+id).val();
        var room_id = $('.room_id_'+id).val();
        var start_date = $('.check_in').val();
        var end_date = $('.check_out').val();

        window.location.href = base_url + "/payment/processPaypal?id=" + id + "&amount=" + amount + "&total_amount=" + total_amount + "&payment_id=" + payment_id + "&property_name=" + property_name + "&hotel_id=" + hotel_id + '&room_id=' + room_id + '&start_date=' + start_date + '&end_date=' + end_date;

        // $.ajax({
        //     url: "{{route('processPaypal')}}",
        //     type: "GET",
        //     data: {id: id,amount: amount,total_amount: total_amount,payment_id: payment_id,property_name: property_name,hotel_id: hotel_id,room_id: room_id,start_date: start_date,end_date: end_date},
        //     success: function (response) {
        //         console.log('succeed');
        //     }, error:function (response) {
        //         console.log('fail');
        //     }
        // });
    });
    
</script>
@endif
@endpush
